### ISSUE TITLE
Auto-Complete don't work

### ISSUE THREAD

**Issue by EQuimper** [nkt/atom-autocomplete-modules#28] opened 2016-05-25 19:01 UTC
Hey, I have this packages for like 3 months and I don't know if the new version of Atom make it don't work but now I lose the autocomplete. I try to reinstall or restart Atom nothing happen. I didn't touch nothing just update Atom to 1.7.4.

**Comment by nkt** [comment] 2016-05-25 21:05
Hmm, every day I also using this plugin. I'll check it as soon as possible.

**Comment by viczam** [comment] 2016-05-25 21:18
yep, after the last update only the `require` calls will display the autocomplete menu

**Comment by insraq** [comment] 2016-05-26 02:27
I can confirm that `import` autocomplete does not work.

**Comment by nkt** [comment] 2016-05-26 10:22
As I see it's broken by 'babel-language' plugin.

**Comment by ajmichaels** [comment] 2016-05-26 18:59
Also having the same issue with language-babel

**Comment by iMasterAle** [comment] 2016-05-27 15:16
Me too.

**Comment by viczam** [comment] 2016-05-29 10:31
I'm using this one while imports are broken - https://atom.io/packages/autocomplete-js-import

**Comment by AveVlad** [comment] 2016-05-30 15:17
+1

**Comment by phyllisstein** [comment] 2016-05-30 19:39
Looks like Babel added a capture for `punctuation.definition.string.begin` to the opening and closing quotation marks in JS string literals, and when the caret is positioned just before the closing quotation mark `autocomplete-plus` uses that as the current scope. My hacky workaround was to change the selector in `completion-provider.js`:

```js
this.selector = '.source.js .string.quoted, .source.js .punctuation.definition.string.begin, .source.coffee .string.quoted';
```

PR, ho!

**Closed** 2016-05-30 20:16 UTC
Labels: bug

**Comment by nkt** [comment] 2016-05-30 20:33
Fixed by @phyllisstein. Published as **1.5.0**.

**Comment by EQuimper** [comment] 2016-05-30 21:11
Good All work thank ;)
