### ISSUE TITLE
Duplicate entries from babel-plugin-module-resolver integration

### ISSUE THREAD

**Issue by jacobmischka** [nkt/atom-autocomplete-modules#99] opened 2018-04-19 16:27 UTC
It looks like there are a lot of duplicates coming from the module-resolver lookup:

![image](https://user-images.githubusercontent.com/3939997/39005022-8c9f4ccc-43c4-11e8-8f28-5655cd5d60da.png)

This wasn't the case a few weeks ago. I'm not sure what's causing it yet.

I'll try to look into it and create a PR soon, but I just wanted to create the issue now while it's on my mind.

Thanks!

**Comment by jonyeezs** [comment] 2018-08-17 12:54
Hi @jacobmischka and @AlexSaenen a new refactored code has been publish.

Found some issues with the code while I was refactoring. Hopefully it would have fixed this issue.

Could you help test to see if it has fixed it.

Thanks!

**Comment by remhume** [comment] 2018-08-17 15:35
I wanted to try it out, but ran into #108 on the way

**Comment by jonyeezs** [comment] 2018-08-17 22:11
@remhume #108 has now been resolved.

**Comment by remhume** [comment] 2018-08-17 22:48
Yes, thanks!

However now the roots set in the babel config does not seem to work anymore at all.

I did some live inspection digging, this is what i found:

My module resolver has this config:
```javascript
{
    root: ['./app'],
}
```
In the folder `app` i have a folder called `components`.
I am now typing `import x from 'compon'`, expecting it to find `components``

However there is no autocomplete result for that.
The reason seems to be `lib/utils/lookup-alias.js`.

the variables contain at execution time:
```javascript
aliases = [{
    expose: ".",
    src: "/Users/remmy/Work/web-frontend/app"
}]

modulePrefix = 'compon';
```


But now the code calls
```javascript
.filter(alias => alias.expose.startsWith(modulePrefix))`
```

As `.` does not start with `compon` my root alias is filtered out.
And there seems to be no other lookup specifically for root, so this might be why i get no results?

**Comment by remhume** [comment] 2018-08-18 00:17
So in your `babel-spec.js`  i found this test for root folders

```javascript
describe('with custom root directories', () => {
        beforeEach(() => {
          v2Config.config.plugins[1] = {
            "root": ["./subfolder"],
            "alias": {
              "wrong": "./subfolder/innerFolder",
              "inny": "./innerFolder" }
          };
          findBabelConfigMock.andReturn(Promise.resolve(v2Config));
        });

        it('should return aliased suggestions', async((done) => {
          subject.getList('inny/function', `${base}/testbed.js`)
          .then((results) => {
            done(() => {
              expect(results.length).toBe(1);
              expect(results[0].text).toBe(`${base}/subfolder/innerFolder`);
            });
          }).catch(e => { throw new Error(e); });
        }));
    });
```

I looked at the fixtures - You may add a test like this one (inside that describe) that should account for my case:

```javascript
it('should return custom root suggestions', async(done => {
    subject
        .getList('namedFunction', `${base}/testbed.js`)
        .then(results => {
            done(() => {
                expect(results).toHaveLength(1);
                expect(results[0].text).toBe(`${base}/subfolder/namedFunction.js`);
            });
        })
        .catch(e => {
            throw new Error(e);
        });
}));
```

Note how the aliases don't matter at all. Specifying a custom root in the babel resolver means that you can access files and folders in the root folder in the same way you'd access them in node_modules.

**Comment by jonyeezs** [comment] 2018-08-18 13:52
@remhume published v2.1.3. cheers!

**Comment by remhume** [comment] 2018-08-18 14:12
Alright the completion works now for the root as before! :) 

However in my project i do see the duplicates again, i'm not sure what of it is different than in your fixtures
<img width="370" alt="screen shot 2018-08-18 at 16 02 57" src="https://user-images.githubusercontent.com/3317423/44300031-8fa3bc00-a300-11e8-9b19-4540a059a14c.png">

Only for the root completions though, node_modules contents are listed once.
It's always exactly 4 repetitions. This has been the behaviour (always with 4 for me) since version 1.13.0, when deep babel lookup was introduced.

I'll try to do some live inspection to find out where the repetitions are coming from.

Relative completions seem to be missing entirely now (`./foo`, `../bar`).

**Comment by remhume** [comment] 2018-08-18 14:28
Found the culprit!

It's this while loop
```
    let currentPath = this.path.dirname(activePanePath);
    // TODO: must be a better way to find all nested babelrc.
    while (currentPath.startsWith(projectPath)) {
      let currentSuggestions = this._generateSuggestion(currentPath, prefix, projectPath);
      suggestionsTotal.push(currentSuggestions);
      currentPath = this.path.resolve(currentPath, '../');
    }
```

In my test cases i was four folders in! and for every while run it would find my babel config in the project folder and get the root completions for it, merging it every time.

The while would

1. take the currentPath `ProjectRoot/app/this/is/aTest.jsx`
2. get the uppermost babelrc (in `ProjectRoot`) and find all completions for it, including root completions
3. now it removes the last part of the path and does it again, finding the same babel config, returning the root completions again. all the way until we ran the while with just 'ProjectRoot', leading to a duplication of root items times PathLength.

I'm not sure how to fix it the best way, but the fixture could be produced by just creating a longer chain of subfolders and lookup somewhere inside there. (i think you use a similar fixture in `module/local-spec.js` already, only that is used to get relative results).

**Comment by jonyeezs** [comment] 2018-08-19 11:07
> It's this while loop

The PR for that is #80 to support nested .babelrc.

Now that we can have some form of unit test, could @lttb or @remhume help with the scenarios to cater nested functionality or if someone can point to me a source that explains the spec for nested babelrc.

Thanks!

**Comment by jonyeezs** [comment] 2018-08-25 03:09
@jacobmischka did mention he had [a fix for this issue in a PR](https://github.com/nkt/atom-autocomplete-modules/pull/102#issuecomment-390460590)

>  I also fixed #99 locally for myself. Once the tests structure in place I might redo the fixes with tests and ask around for what the spec of the nested .babelrc feauture was.

@remhume you're spot on, that's where the problem is.

I'm thinking to remove the while loop.

I'm not familiar with any scenarios of nested `babelrc`s. And i would imagine you'd only want to use the configs of the closest babel to your working file, which the library `find-babel-config` does. That should satisfy the scenario of nested configs, i reckon?

Would love some feedback so we can resolve this long standing issue.

Thanks folks!

**Comment by vitexikora** [comment] 2018-10-22 09:59
How is it looking?
I spent couple hours trying to figure this out 😢  First, the autocompletition stopped working for me (I was using webpack moduleDirs), and then I installed the babel resolver additionally, just to get it working and this buffled me heavily.. I thought I have it badly configured, so I tried like 100 possible module-resolver configurations 🤣 
So if you have exactly these symptoms, this is the way out:
```
apm uninstall autocomplete-modules
apm i autocomplete-modules@1.12.0
```

**Comment by jonyeezs** [comment] 2018-10-25 12:41
Currently working on a fix for this issue

**Closed** 2018-10-27 07:17 UTC
Labels: bug
